org.gradle.jvmargs=-Xmx3G -XX:MaxMetaspaceSize=1G -XX:ReservedCodeCacheSize=256m -XX:+HeapDumpOnOutOfMemoryError
org.gradle.parallel=true
org.gradle.daemon=false
org.gradle.workers.max=4
android.useAndroidX=true
android.enableJetifier=false
kotlin.incremental=false
android.builtInKotlin=false
android.newDsl=false
